"""Operational contracts for the Wirtelprimpf publication platform."""

from .naming import (
    ARCHIVE_CAPACITY,
    BOOKS_PER_ARCHIVE,
    STORIES_PER_BOOK,
    ArchiveTarget,
    BookTarget,
    archive_target_for_volume,
    book_target_for_story,
)
from .state import PlatformState, RotationPhase
from .story_blueprint import (
    STORY_BLUEPRINT_VERSION,
    STORY_STATE_VERSION,
    StoryBlueprintError,
    StoryCheckpoint,
    advance_checkpoint,
    blueprint_sha256,
    choose_decision,
    exclusive_story_checkpoint_lock,
    select_bounded_traits,
    start_story,
    start_next_story,
    validate_story_blueprint,
)
from .cloudflare_aliases import (
    ALIAS_GROUP_SIZE,
    ALIAS_LABEL_MAX_LENGTH,
    CATALOG_VERSION,
    EXPECTED_GROUPS,
    EXPECTED_GROUP_TARGETS,
    NUMERIC_REDIRECT_EXPRESSION,
    AliasCatalog,
    CloudflareAliasError,
    load_alias_catalog,
    numeric_alias_host,
    numeric_alias_number,
    numeric_redirect_location,
    validate_alias_catalog,
)
from .cloudflare_snapshot import (
    SNAPSHOT_VERSION,
    CloudflareSnapshotError,
    read_snapshot,
    validate_snapshot,
    write_snapshot,
)
from .cloudflare_preflight import (
    ALIAS_RECORD_COMMENT,
    ALIAS_RECORD_CONTENT,
    CloudflarePreflightError,
    PreflightReport,
    build_alias_record_payloads,
    validate_preflight,
)
from .cloudflare_rollback import (
    ROLLBACK_SEQUENCE,
    CloudflareRollbackError,
    RollbackPlan,
    build_rollback_plan,
)
from .cloudflare_audit import (
    DNS_QUOTA_LIMIT,
    RULESET_PHASE,
    CloudflareAuditError,
    collect_snapshot,
)

__all__ = [
    "ARCHIVE_CAPACITY",
    "BOOKS_PER_ARCHIVE",
    "STORIES_PER_BOOK",
    "ArchiveTarget",
    "BookTarget",
    "PlatformState",
    "RotationPhase",
    "archive_target_for_volume",
    "book_target_for_story",
    "STORY_BLUEPRINT_VERSION",
    "STORY_STATE_VERSION",
    "StoryBlueprintError",
    "StoryCheckpoint",
    "advance_checkpoint",
    "blueprint_sha256",
    "choose_decision",
    "exclusive_story_checkpoint_lock",
    "select_bounded_traits",
    "start_story",
    "start_next_story",
    "validate_story_blueprint",
    "ALIAS_GROUP_SIZE",
    "ALIAS_LABEL_MAX_LENGTH",
    "CATALOG_VERSION",
    "EXPECTED_GROUPS",
    "EXPECTED_GROUP_TARGETS",
    "NUMERIC_REDIRECT_EXPRESSION",
    "AliasCatalog",
    "CloudflareAliasError",
    "load_alias_catalog",
    "numeric_alias_host",
    "numeric_alias_number",
    "numeric_redirect_location",
    "validate_alias_catalog",
    "SNAPSHOT_VERSION",
    "CloudflareSnapshotError",
    "read_snapshot",
    "validate_snapshot",
    "write_snapshot",
    "ALIAS_RECORD_COMMENT",
    "ALIAS_RECORD_CONTENT",
    "CloudflarePreflightError",
    "PreflightReport",
    "build_alias_record_payloads",
    "validate_preflight",
    "ROLLBACK_SEQUENCE",
    "CloudflareRollbackError",
    "RollbackPlan",
    "build_rollback_plan",
    "DNS_QUOTA_LIMIT",
    "RULESET_PHASE",
    "CloudflareAuditError",
    "collect_snapshot",
]

__version__ = "1.1.0"
