name: check

on:
  push:
  pull_request:

jobs:
  applet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            Makefile
            Sourcecode
            files
            scripts
            tests
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: make check
